export const PTE_CORE_PREMIUM_PRODUCT_NAME = 'PTE Core Premium';
export const PTE_CORE_PREMIUM_PRICE_CAD = 20;
export const PTE_CORE_PREMIUM_BILLING_INTERVAL = 'month';
export const PTE_CORE_FREE_ATTEMPTS_PER_MODE = 1;
