export const PTE_CORE_EXAM_KEY = 'PTE_CORE';
export const PTE_CORE_BASE_PATH = '/pte-core';

export const PTE_CORE_ROUTE_MAP = {
  hub: PTE_CORE_BASE_PATH,
  listening: `${PTE_CORE_BASE_PATH}/listening`,
  reading: `${PTE_CORE_BASE_PATH}/reading`,
  writing: `${PTE_CORE_BASE_PATH}/writing`,
  speaking: `${PTE_CORE_BASE_PATH}/speaking`,
  simulator: `${PTE_CORE_BASE_PATH}/simulator`,
  simulatorPractice: `${PTE_CORE_BASE_PATH}/simulator/practice`,
  questionTypes: `${PTE_CORE_BASE_PATH}/question-types`,
};

export const PTE_CORE_SKILLS = [
  {
    slug: 'listening',
    label: 'Listening',
    path: `${PTE_CORE_BASE_PATH}/listening`,
    sectionId: 'listening',
    heroImage: '/heroes/listening.png',
    eyebrow: 'PTE Core Listening',
    heroTitle: 'Catch the meaning once, then answer with calm precision.',
    description: 'Build accuracy under one-play audio pressure and recover from missed detail quickly.',
    promise: 'Train note capture, distractor control, and transcript discipline before audio speed starts to feel chaotic.',
    accent: 'sky',
    metrics: ['7 listening tasks', '30 minute section', 'One-play audio'],
    focusPoints: [
      'Predict the answer type before the audio starts.',
      'Track speaker intention instead of isolated keywords.',
      'Recover cleanly after missed words without losing the next detail.',
    ],
    featuredQuestionSlugs: [
      'summarize-spoken-text',
      'multiple-choice-multiple-answers-listening',
      'write-from-dictation',
    ],
  },
  {
    slug: 'reading',
    label: 'Reading',
    path: `${PTE_CORE_BASE_PATH}/reading`,
    sectionId: 'reading',
    heroImage: '/heroes/reading.png',
    eyebrow: 'PTE Core Reading',
    heroTitle: 'Turn every reading answer into an evidence decision.',
    description: 'Train passage control, evidence matching, and time-safe answer decisions.',
    promise: 'Build a question-type routine for grammar, cohesion, and proof-based elimination under time pressure.',
    accent: 'gold',
    metrics: ['5 reading tasks', '32 minute section', 'Evidence-first strategy'],
    focusPoints: [
      'Separate grammar clues from meaning clues in fill-in-the-blanks tasks.',
      'Use cohesion markers to rebuild paragraph order.',
      'Eliminate attractive distractors with direct text proof.',
    ],
    featuredQuestionSlugs: [
      'reading-writing-fill-in-the-blanks',
      'reorder-paragraphs',
      'multiple-choice-single-answer-reading',
    ],
  },
  {
    slug: 'writing',
    label: 'Writing',
    path: `${PTE_CORE_BASE_PATH}/writing`,
    sectionId: 'speaking-writing',
    heroImage: '/heroes/writing.png',
    eyebrow: 'PTE Core Writing',
    heroTitle: 'Write clean, score-safe responses without overthinking the clock.',
    description: 'Improve structure, grammar control, and concise task execution for PTE Core writing tasks.',
    promise: 'Build a practical writing workflow for summaries and emails: plan fast, cover the task, and keep grammar controlled.',
    accent: 'coral',
    metrics: ['2 writing tasks', 'Integrated section', 'Structure + accuracy'],
    focusPoints: [
      'Compress a passage into one complete sentence without losing the main idea.',
      'Write emails that cover purpose, details, tone, and closing cleanly.',
      'Use sentence control instead of risky complexity when time is tight.',
    ],
    featuredQuestionSlugs: [
      'summarize-written-text',
      'write-email',
      'reading-writing-fill-in-the-blanks',
    ],
  },
  {
    slug: 'speaking',
    label: 'Speaking',
    path: `${PTE_CORE_BASE_PATH}/speaking`,
    sectionId: 'speaking-writing',
    heroImage: '/heroes/speaking.png',
    eyebrow: 'PTE Core Speaking',
    heroTitle: 'Speak with rhythm, clarity, and a plan for every prompt.',
    description: 'Strengthen fluency, pronunciation, and response structure for spoken tasks.',
    promise: 'Practice short preparation routines that keep your answer moving, organized, and easy to understand.',
    accent: 'ink',
    metrics: ['5 speaking tasks', 'Timed responses', 'Fluency + clarity'],
    focusPoints: [
      'Keep delivery smooth even when the sentence or image feels unfamiliar.',
      'Use simple response frames for situations and short questions.',
      'Prioritize intelligibility, pacing, and complete task coverage.',
    ],
    featuredQuestionSlugs: [
      'read-aloud',
      'describe-image',
      'respond-to-a-situation',
    ],
  },
];

export const PTE_CORE_QUESTION_TYPES = [
  {
    slug: 'read-aloud',
    label: 'Read Aloud',
    section: 'speaking-writing',
    summary: 'Read a short text clearly with strong pronunciation and steady pace.',
  },
  {
    slug: 'repeat-sentence',
    label: 'Repeat Sentence',
    section: 'speaking-writing',
    summary: 'Listen once and repeat the sentence accurately with clear delivery.',
  },
  {
    slug: 'describe-image',
    label: 'Describe Image',
    section: 'speaking-writing',
    summary: 'Describe visual data with structure, relevance, and controlled language.',
  },
  {
    slug: 'respond-to-a-situation',
    label: 'Respond to a Situation',
    section: 'speaking-writing',
    summary: 'Deliver a practical spoken response for a real-world prompt.',
  },
  {
    slug: 'answer-short-question',
    label: 'Answer Short Question',
    section: 'speaking-writing',
    summary: 'Give brief and accurate spoken answers to simple prompts.',
  },
  {
    slug: 'summarize-written-text',
    label: 'Summarize Written Text',
    section: 'speaking-writing',
    summary: 'Condense a written passage into one clear, complete summary sentence.',
  },
  {
    slug: 'write-email',
    label: 'Write Email',
    section: 'speaking-writing',
    summary: 'Write an organized and purpose-driven email with strong language control.',
  },
  {
    slug: 'reading-writing-fill-in-the-blanks',
    label: 'Reading & Writing: Fill in the Blanks',
    section: 'reading',
    summary: 'Choose the best word choices from dropdowns based on context and grammar.',
  },
  {
    slug: 'multiple-choice-multiple-answers-reading',
    label: 'Multiple Choice, Multiple Answers (Reading)',
    section: 'reading',
    summary: 'Select all correct options based on close meaning and textual evidence.',
  },
  {
    slug: 'reorder-paragraphs',
    label: 'Reorder Paragraphs',
    section: 'reading',
    summary: 'Rebuild paragraph sequence using logic, cohesion, and reference clues.',
  },
  {
    slug: 'fill-in-the-blanks-reading',
    label: 'Fill in the Blanks (Reading)',
    section: 'reading',
    summary: 'Drag the correct words into blank spaces while preserving meaning and grammar.',
  },
  {
    slug: 'multiple-choice-single-answer-reading',
    label: 'Multiple Choice, Single Answer (Reading)',
    section: 'reading',
    summary: 'Choose one best answer with direct text support and distractor control.',
  },
  {
    slug: 'summarize-spoken-text',
    label: 'Summarize Spoken Text',
    section: 'listening',
    summary: 'Listen and write a concise summary capturing the main points accurately.',
  },
  {
    slug: 'multiple-choice-multiple-answers-listening',
    label: 'Multiple Choice, Multiple Answers (Listening)',
    section: 'listening',
    summary: 'Select all valid answers from audio using detail and meaning checks.',
  },
  {
    slug: 'fill-in-the-blanks-listening',
    label: 'Fill in the Blanks (Listening)',
    section: 'listening',
    summary: 'Type missing words from audio with strong spelling and attention control.',
  },
  {
    slug: 'multiple-choice-single-answer-listening',
    label: 'Multiple Choice, Single Answer (Listening)',
    section: 'listening',
    summary: 'Identify the one best answer from a spoken prompt and choices.',
  },
  {
    slug: 'select-missing-word',
    label: 'Select Missing Word',
    section: 'listening',
    summary: 'Choose the best ending after hearing an interrupted audio segment.',
  },
  {
    slug: 'highlight-incorrect-words',
    label: 'Highlight Incorrect Words',
    section: 'listening',
    summary: 'Track mismatch between transcript and audio by marking changed words.',
  },
  {
    slug: 'write-from-dictation',
    label: 'Write from Dictation',
    section: 'listening',
    summary: 'Write the sentence exactly as heard with correct spelling and punctuation.',
  },
];

export const PTE_CORE_SEO_KEYWORDS = [
  'PTE Core preparation',
  'PTE Core practice test',
  'PTE Core simulator',
  'PTE Core writing practice',
  'PTE Core speaking practice',
  'PTE Core reading question types',
  'PTE Core listening question types',
  'PTE Core Canada immigration',
];

export const PTE_CORE_PAGE_KEYWORDS = PTE_CORE_SEO_KEYWORDS.join(', ');

export const PTE_CORE_SIMULATOR_SECTIONS = [
  {
    id: 'speaking-writing',
    label: 'Part 1',
    title: 'Speaking and Writing',
    durationMinutes: 54,
    description: 'Integrated speaking and writing tasks with short preparation windows and typed responses.',
    questionTypeSlugs: [
      'read-aloud',
      'repeat-sentence',
      'describe-image',
      'respond-to-a-situation',
      'answer-short-question',
      'summarize-written-text',
      'write-email',
    ],
  },
  {
    id: 'reading',
    label: 'Part 2',
    title: 'Reading',
    durationMinutes: 32,
    description: 'Reading tasks focused on grammar, cohesion, close meaning, and evidence control.',
    questionTypeSlugs: [
      'reading-writing-fill-in-the-blanks',
      'multiple-choice-multiple-answers-reading',
      'reorder-paragraphs',
      'fill-in-the-blanks-reading',
      'multiple-choice-single-answer-reading',
    ],
  },
  {
    id: 'listening',
    label: 'Part 3',
    title: 'Listening',
    durationMinutes: 30,
    description: 'Listening tasks that use transcript-style placeholders until audio and microphone slices are added.',
    questionTypeSlugs: [
      'summarize-spoken-text',
      'multiple-choice-multiple-answers-listening',
      'fill-in-the-blanks-listening',
      'multiple-choice-single-answer-listening',
      'select-missing-word',
      'highlight-incorrect-words',
      'write-from-dictation',
    ],
  },
];

export const PTE_CORE_SIMULATOR_TOTAL_MINUTES = PTE_CORE_SIMULATOR_SECTIONS.reduce(
  (total, section) => total + section.durationMinutes,
  0,
);

export const PTE_CORE_SIMULATOR_SAMPLE_ITEMS = [
  {
    id: 'pte-sw-01',
    number: 1,
    sectionId: 'speaking-writing',
    taskSlug: 'read-aloud',
    prompt:
      'Community libraries are changing quickly. Many now provide language workshops, digital learning spaces, and settlement resources for newcomers.',
    instructions: 'Read the text aloud. In this slice, use the response box to note whether your delivery felt clear and complete.',
    responseType: 'speaking-note',
    prepSeconds: 30,
    responseSeconds: 40,
  },
  {
    id: 'pte-sw-02',
    number: 2,
    sectionId: 'speaking-writing',
    taskSlug: 'repeat-sentence',
    prompt: 'Audio placeholder: The registration deadline has been extended until Friday afternoon.',
    instructions: 'Listen once and repeat the sentence. Audio playback is added in a later slice.',
    responseType: 'speaking-note',
    prepSeconds: 0,
    responseSeconds: 15,
  },
  {
    id: 'pte-sw-03',
    number: 3,
    sectionId: 'speaking-writing',
    taskSlug: 'describe-image',
    prompt:
      'Image placeholder: A line chart shows steady growth in online course enrolment from 2020 to 2024, with the sharpest increase after 2022.',
    instructions: 'Plan a short description with an introduction, key trend, and closing comparison.',
    responseType: 'speaking-note',
    prepSeconds: 25,
    responseSeconds: 40,
  },
  {
    id: 'pte-sw-04',
    number: 4,
    sectionId: 'speaking-writing',
    taskSlug: 'respond-to-a-situation',
    prompt:
      'You borrowed a laptop from your college library and noticed the charger is missing. Leave a message explaining the problem and asking what to do next.',
    instructions: 'Prepare a practical spoken response. Keep it polite, specific, and easy to follow.',
    responseType: 'speaking-note',
    prepSeconds: 20,
    responseSeconds: 40,
  },
  {
    id: 'pte-sw-05',
    number: 5,
    sectionId: 'speaking-writing',
    taskSlug: 'answer-short-question',
    prompt: 'What do we call the document that lists your work history and education when applying for a job?',
    instructions: 'Type the short answer you would say aloud.',
    responseType: 'text',
  },
  {
    id: 'pte-sw-06',
    number: 6,
    sectionId: 'speaking-writing',
    taskSlug: 'summarize-written-text',
    prompt:
      'Remote work has allowed many employees to live farther from city centres, but it has also changed how teams communicate. Companies now rely more on written updates, scheduled check-ins, and clear project documentation to keep collaboration efficient.',
    instructions: 'Write one sentence that summarizes the passage.',
    responseType: 'textarea',
    minWords: 5,
    maxWords: 75,
  },
  {
    id: 'pte-sw-07',
    number: 7,
    sectionId: 'speaking-writing',
    taskSlug: 'write-email',
    prompt:
      'Write an email to a community centre asking about evening English classes. Ask about the schedule, cost, and registration process.',
    instructions: 'Write a clear email with a greeting, purpose, details, and closing.',
    responseType: 'textarea',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'pte-r-01',
    number: 8,
    sectionId: 'reading',
    taskSlug: 'reading-writing-fill-in-the-blanks',
    prompt:
      'Many adults choose online courses because they are flexible and can be completed at a ___ pace.',
    instructions: 'Choose the word that best completes the sentence.',
    responseType: 'single',
    options: ['steady', 'personal', 'private', 'regular'],
  },
  {
    id: 'pte-r-02',
    number: 9,
    sectionId: 'reading',
    taskSlug: 'multiple-choice-multiple-answers-reading',
    prompt:
      'A notice says that residents can renew parking permits online, by mail, or in person. Online renewals are processed immediately, while mailed forms may take ten business days.',
    instructions: 'Select all statements supported by the notice.',
    responseType: 'multiple',
    options: [
      'Residents have more than one renewal method.',
      'Online renewals are the fastest option.',
      'Mailed forms are processed on weekends.',
      'Permits can only be renewed in person.',
    ],
  },
  {
    id: 'pte-r-03',
    number: 10,
    sectionId: 'reading',
    taskSlug: 'reorder-paragraphs',
    prompt:
      'A. Finally, applicants receive a confirmation email. B. First, they create an online profile. C. Next, they upload supporting documents.',
    instructions: 'Type the correct order of the paragraphs, such as B, C, A.',
    responseType: 'text',
  },
  {
    id: 'pte-r-04',
    number: 11,
    sectionId: 'reading',
    taskSlug: 'fill-in-the-blanks-reading',
    prompt:
      'The museum has expanded its weekend programs to attract more families and make the exhibits more ___.',
    instructions: 'Type the best missing word.',
    responseType: 'text',
  },
  {
    id: 'pte-r-05',
    number: 12,
    sectionId: 'reading',
    taskSlug: 'multiple-choice-single-answer-reading',
    prompt:
      'A short article explains that public bike lanes reduce traffic pressure, improve safety for cyclists, and encourage healthier commuting habits.',
    instructions: 'Choose the best main idea.',
    responseType: 'single',
    options: [
      'Bike lanes can support safer and healthier city travel.',
      'Cyclists should avoid busy streets.',
      'Public transit is more reliable than driving.',
      'Traffic pressure is caused only by parking shortages.',
    ],
  },
  {
    id: 'pte-l-01',
    number: 13,
    sectionId: 'listening',
    taskSlug: 'summarize-spoken-text',
    prompt:
      'Audio placeholder: A speaker explains that neighbourhood gardens help residents access fresh food, meet neighbours, and learn practical growing skills.',
    instructions: 'Write a concise summary of the audio.',
    responseType: 'textarea',
    minWords: 20,
    maxWords: 70,
  },
  {
    id: 'pte-l-02',
    number: 14,
    sectionId: 'listening',
    taskSlug: 'multiple-choice-multiple-answers-listening',
    prompt:
      'Audio placeholder: The speaker says the workshop includes resume feedback, interview practice, and a short networking session.',
    instructions: 'Select all activities mentioned.',
    responseType: 'multiple',
    options: ['Resume feedback', 'Interview practice', 'Networking session', 'A written grammar exam'],
  },
  {
    id: 'pte-l-03',
    number: 15,
    sectionId: 'listening',
    taskSlug: 'fill-in-the-blanks-listening',
    prompt: 'Audio placeholder transcript: The next train to downtown will arrive on platform ___.',
    instructions: 'Type the missing word or number.',
    responseType: 'text',
  },
  {
    id: 'pte-l-04',
    number: 16,
    sectionId: 'listening',
    taskSlug: 'multiple-choice-single-answer-listening',
    prompt: 'Audio placeholder: A caller asks to change an appointment because of a work conflict.',
    instructions: 'Choose the main reason for the call.',
    responseType: 'single',
    options: [
      'To reschedule an appointment',
      'To complain about a bill',
      'To apply for a job',
      'To request directions',
    ],
  },
  {
    id: 'pte-l-05',
    number: 17,
    sectionId: 'listening',
    taskSlug: 'select-missing-word',
    prompt:
      'Audio placeholder: The speaker says the new community centre will open next month, but membership registration begins ___.',
    instructions: 'Choose the most logical ending.',
    responseType: 'single',
    options: ['tomorrow', 'last year', 'after midnight in 2035', 'never'],
  },
  {
    id: 'pte-l-06',
    number: 18,
    sectionId: 'listening',
    taskSlug: 'highlight-incorrect-words',
    prompt:
      'Transcript placeholder: The manager confirmed that the safety training will happen on Tuesday morning in room fourteen.',
    instructions: 'Type any words that sound different from the audio when audio is added in a later slice.',
    responseType: 'text',
  },
  {
    id: 'pte-l-07',
    number: 19,
    sectionId: 'listening',
    taskSlug: 'write-from-dictation',
    prompt: 'Audio placeholder: The final report must be submitted before the end of the week.',
    instructions: 'Write the sentence exactly as heard.',
    responseType: 'text',
  },
];

export function getPteQuestionTypeBySlug(slug) {
  return PTE_CORE_QUESTION_TYPES.find((questionType) => questionType.slug === slug);
}
